/*
 * choiceFrame.java
 *
 * Created on December 29, 2003, 10:51 PM
 */

package client;

import java.awt.*;
import javax.swing.*;

/**
 *
 * @author  mfahim
 */
public class choiceFrame extends javax.swing.JFrame {

    /** Creates new form choiceFrame */
    public choiceFrame() {
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("src/images/icon.png"));
        this.setTitle("Main");
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();  
        Rectangle recframe = getBounds();  
        setLocation((screen.width - recframe.width)/2, (screen.height - recframe.height)/2);  
    }
    public choiceFrame(JFrame f) {
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("src/images/icon.png"));
        this.setTitle("Main");
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();  
        Rectangle recframe = getBounds();  
        setLocation((screen.width - recframe.width)/2, (screen.height - recframe.height)/2);  
        frame = new JFrame();
        frame = f;
        f.setVisible(false);
        f.dispose();
        
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        choicePanel = new javax.swing.JPanel();
        gotoAdmin = new javax.swing.JButton();
        gotoEmp = new javax.swing.JButton();
        gotoExit = new javax.swing.JButton();
        gotoMan = new javax.swing.JButton();
        vmLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        gotoAdmin.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        gotoAdmin.setText("Administrator");
        gotoAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gotoAdminActionPerformed(evt);
            }
        });

        gotoEmp.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        gotoEmp.setText("Employee");
        gotoEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gotoEmpActionPerformed(evt);
            }
        });

        gotoExit.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        gotoExit.setText("Exit");
        gotoExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gotoExitActionPerformed(evt);
            }
        });

        gotoMan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        gotoMan.setText("Manager");
        gotoMan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gotoManActionPerformed(evt);
            }
        });

        vmLogo.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        vmLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vmLogo.setText("Value Mart");

        org.jdesktop.layout.GroupLayout choicePanelLayout = new org.jdesktop.layout.GroupLayout(choicePanel);
        choicePanel.setLayout(choicePanelLayout);
        choicePanelLayout.setHorizontalGroup(
            choicePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(choicePanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(gotoExit)
                .addContainerGap(317, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, vmLogo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
            .add(choicePanelLayout.createSequentialGroup()
                .add(104, 104, 104)
                .add(choicePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(gotoEmp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 173, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(gotoAdmin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 173, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(gotoMan, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 173, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        choicePanelLayout.setVerticalGroup(
            choicePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, choicePanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(vmLogo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .add(30, 30, 30)
                .add(gotoAdmin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(gotoMan, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(gotoEmp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(33, 33, 33)
                .add(gotoExit)
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(choicePanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 300, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(choicePanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void gotoExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gotoExitActionPerformed
    System.exit(0);
}//GEN-LAST:event_gotoExitActionPerformed

private void gotoAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gotoAdminActionPerformed
    this.setVisible(false);
    adminLogFrame adFrame = new adminLogFrame();
    adFrame.setVisible(true);
    this.dispose();
}//GEN-LAST:event_gotoAdminActionPerformed

private void gotoManActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gotoManActionPerformed
    this.setVisible(false);
    manLogFrame maFrame = new manLogFrame();
    maFrame.setVisible(true);
    this.dispose();
}//GEN-LAST:event_gotoManActionPerformed

private void gotoEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gotoEmpActionPerformed
    this.setVisible(false);
    empLogFrame epFrame = new empLogFrame();
    epFrame.setVisible(true);
    this.dispose();
}//GEN-LAST:event_gotoEmpActionPerformed

    private javax.swing.JFrame frame;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel choicePanel;
    private javax.swing.JButton gotoAdmin;
    private javax.swing.JButton gotoEmp;
    private javax.swing.JButton gotoExit;
    private javax.swing.JButton gotoMan;
    private javax.swing.JLabel vmLogo;
    // End of variables declaration//GEN-END:variables

}
