/*
 * NewJFrame.java
 *
 * Created on January 12, 2012, 6:43 PM
 */

package server;

import java.awt.Toolkit;

/**
 *
 * @author  mfahim
 */
public class serverFrame extends javax.swing.JFrame {

    /** Creates new form NewJFrame */
    public serverFrame() {
        initComponents();
        this.setTitle("Server Status");
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("src/images/icon.png"));
        //sCom = new String();
    }
    public void setInsertStatus (String s){
        //sCom.concat(s);
        clientInsertReq.append(s + newline);
    }
    public void setUpdateStatus (String s){
        //sCom.concat(s);
        clientUpdateReq.append(s + newline);
    }
    public void setDeleteStatus (String s){
        //sCom.concat(s);
        clientDeleteReq.append(s + newline);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        serverPane = new javax.swing.JPanel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        clientInsertReq = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        clientUpdateReq = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        clientDeleteReq = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        clientQueryReq = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        clientInsertReq.setColumns(20);
        clientInsertReq.setEditable(false);
        clientInsertReq.setRows(5);
        jScrollPane2.setViewportView(clientInsertReq);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 506, Short.MAX_VALUE)
            .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 139, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
        );

        jTabbedPane4.addTab("Insert Request", jPanel1);

        clientUpdateReq.setColumns(20);
        clientUpdateReq.setEditable(false);
        clientUpdateReq.setRows(5);
        jScrollPane1.setViewportView(clientUpdateReq);

        org.jdesktop.layout.GroupLayout jPanel5Layout = new org.jdesktop.layout.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
        );

        jTabbedPane4.addTab("Update Request", jPanel5);

        clientDeleteReq.setColumns(20);
        clientDeleteReq.setEditable(false);
        clientDeleteReq.setRows(5);
        jScrollPane3.setViewportView(clientDeleteReq);

        jTabbedPane4.addTab("Delete Request", jScrollPane3);

        clientQueryReq.setColumns(20);
        clientQueryReq.setEditable(false);
        clientQueryReq.setRows(5);
        jScrollPane4.setViewportView(clientQueryReq);

        jTabbedPane4.addTab("Query Request", jScrollPane4);

        org.jdesktop.layout.GroupLayout serverPaneLayout = new org.jdesktop.layout.GroupLayout(serverPane);
        serverPane.setLayout(serverPaneLayout);
        serverPaneLayout.setHorizontalGroup(
            serverPaneLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(serverPaneLayout.createSequentialGroup()
                .addContainerGap()
                .add(jTabbedPane4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
                .addContainerGap())
        );
        serverPaneLayout.setVerticalGroup(
            serverPaneLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, serverPaneLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jTabbedPane4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 167, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(84, 84, 84))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(serverPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(serverPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 182, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //private String sCom;
    private final static String newline = "\n";
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea clientDeleteReq;
    private javax.swing.JTextArea clientInsertReq;
    private javax.swing.JTextArea clientQueryReq;
    private javax.swing.JTextArea clientUpdateReq;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JPanel serverPane;
    // End of variables declaration//GEN-END:variables

}
